### ISSUE TITLE
Adicionar descrições em inglês

### ISSUE THREAD

**Issue by hattori-dev** [hattori-dev/monero-lazy-monitor#1]
O titulo diz tudo ou como diria o ZéZé : "the tittle says it all"

**Comment by hattori-dev** [comment]
Falarei com o conselheiro ZéZé para ele me ajudar na tradução

**Comment by kic0** [comment]
I can help! :)

**Comment by hattori-dev** [comment]
Already fired ZéZé Camarinha and looking forward to work with you @kic0
